---
apiVersion: v1
kind: Namespace
metadata:
  name: iptables-viz
---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iptables-viz-backend-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iptables-viz-backend-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iptables-viz-backend-role
subjects:
  - kind: ServiceAccount
    name: iptables-viz-backend-sa
    namespace: iptables-viz
---

---

---

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iptables-viz-frontend-role
  namespace: iptables-viz
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["iptables-viz-backend-svc"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iptables-viz-frontend-binding
  namespace: iptables-viz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: iptables-viz-frontend-role
subjects:
  - kind: ServiceAccount
    name: iptables-viz-frontend-sa
    namespace: iptables-viz
---


