{{- if .Values.serviceAccount.backend.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "iptables-viz.backendServiceAccountName" . }}
  labels:
    {{- include "iptables-viz.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}