apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "iptables-viz.fullname" . }}-backend-role
  namespace: {{ default .Values.namespace "kube-system" }}
  labels:
    {{- include "iptables-viz.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]