apiVersion: v1
kind: Service
metadata:
  name: iptables-viz-backend-svc
  namespace: iptables-viz
spec:
  selector:
    app: iptables-viz-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: iptables-viz-frontend-svc
  namespace: iptables-viz
spec:
  type: NodePort
  selector:
    app: iptables-viz-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30025